### ISSUE TITLE
Enhance elastic search mapping for documents

### ISSUE THREAD

**Issue by sebastiendeleze** [rero/sonar#139]
* AND instead of OR (simple query of ES) everywhere
    * Search has to manage diacritics, as in RERO ILS
    * User search: it should be possible to do a keyword search (for a user search, we cannot search by using only the last name) > check field analyser
    * Ranking by relevance (might not be necessary with the new AND instead of OR)
    * Full text search disabled.

**Comment by sebastiendeleze** [comment]
@pronguen I think the `OR` operator is already implemented by default for all searches. For instance, in this document https://sonardev.test.rero.ch/api/documents/168, you can do a search with terms appearing in different fields and the document is returned https://sonardev.test.rero.ch/global/search/documents?q=Testing%202019&page=5&size=10 (last record of the page).
Maybe I missunderstood something...

**Comment by pronguen** [comment]
Yes, by now we have `OR` but we want `AND` as default operator. 

Example: https://sonardev.test.rero.ch/global/search/documents?q=Testing%20AND%202019&page=1&size=10
* it corresponds better to the request "testing 2019" with only 2 results
* what is more, the document with title "Testing" should appear at first rank. Could you check the default sort option by relevance?
* I don't understand why the other document appears in the result as it does not contain "2019"

**Comment by mmo** [comment]
- OK: AND instead of OR
- OK: diacritics replacement, eg. universitaeten / universitaten -> universitäten
- OK: User search
- Ranking by relevance: more data needed for testing
- OK: Full text search
