### ISSUE TITLE
Group users by sections

### ISSUE THREAD

**Issue by sebastiendeleze** [rero/sonar#145]
For managing access to certain actions for an entire group of users.

- [ ] Create a new `section` resource.
- [ ] Associate multiple sections in an organisation.
- [ ] Select one or more section in the document editor.
- [ ] Associate a section to an user.
- [ ] Add the possibility to select one or more sections in deposit process (step diffusion).
- [ ] Add a facet to filter deposits by section.
- [ ] Add a facet to filter documents by section.
- [ ] Restrict the access to a document (edition, deletion) to users that belong to the same section.

**Comment by pronguen** [comment]
To be clarified with @mmo:
* is this the subdivision of an organisation into departments/faculties?
* check how RERO DOC manages this
* specification to be detailed

**Comment by pronguen** [comment]
@sebastiendeleze It already works really good! I have some comments. Nothing is really blocking. I marked the most important points with **(!)**.

- [ ] Permissions
    - [ ] **(!)** User of another subdivision should be able to display the document detailed view of all his/her organisation's documents. Currently, it is blocked.
    - [ ] A moderator of a subdivision can see, edit and delete deposits of other subdivisions. He/she should not be able to see/edit/delete them. He/she should not have the "Subdivision" facet. His/her deposit brief view filters the deposit to his/her subdivision.
    - [ ] A moderator should not be able to add/edit a subdivision to his/her organisation. I would even hide the menu.
        - [ ] By the way, this applies also to collections.
    - [ ] **(!)** An administrator should be able to edit/add/delete all deposits/documents of his/her organisation, even if they are not of his/her subdivision.
- [ ] Display
    - [ ] **(!)** Facet values of the (user|document|deposit) brief view are not translated. Concerns also the document brief view on the pro interface.
    - [ ] In the user brief view, it would be nice to display the subdivision of each user next to his/her organisation.
    - [ ] **(!)** Find a way to display the subdivision of a document on detailed view (public and professional)
        - [ ] Currently, the organisation name is not displayed. I would display these two info together (see RERO DOC example)
        - [ ] should we display it in evidence?
            - [ ] it is already displayed on document detailed view (pro), but a bit hidden in the other fields.
            - [ ] in evidence, for instance above the document title, in form of a bootstrap secondary badge with organisation name and subdivsion name if it exists.
        - [ ] don't put the label "Subdivision", which is not for end users
        - [ ] apply the same display in public an pro interface
        - [ ] display it also on brief view? To clarify with @mmo
- [ ] SONAR organisation / menus
    - [ ] For the admin menu, I would group the resources available to the admin in one menu "Administration": Collections, Organisations, Subdivisions, Users
        - [ ] All the menus would then be: Administration, Documents, Research projects, Deposits
    - [ ] It would be nice to list the subdivisions in the organisation detailed view, with links to the detailed view. Nice to have: links to edit/add/delete one. Ex: locations within a library in RERO ILS.
        - [ ] Same for the collections

**Comment by pronguen** [comment]
- [ ] When depositing as a submitter, in the last step I have the subdivision field.
    - [ ] The suggestions in this field don't work.
    - [ ] A submitter attached to a subdivision should not have to fill this field (either it is prefilled and hidden, or prefilled and editable)
    - [ ] The submitters/researchers don't understand what a "subdivision" ist. If the field is show, we need a description, or at least a tooltip: "Department, institute or other subdivision of the institution"

**Comment by sebastiendeleze** [comment]
> * [ ]  When depositing as a submitter, in the last step I have the subdivision field.
>   
>   * [ ]  The suggestions in this field don't work.
>   * [ ]  A submitter attached to a subdivision should not have to fill this field (either it is prefilled and hidden, or prefilled and editable)
>   * [ ]  The submitters/researchers don't understand what a "subdivision" ist. If the field is show, we need a description, or at least a tooltip: "Department, institute or other subdivision of the institution"
> * [ ]  [low priority] Editing a subdivision or a collection: I should not be able to define more than one name per language.
> * [ ]  (!) **NOT SOLVED** Facet values of the (user|document|deposit) brief view are not translated. Concerns also the document brief view on the pro interface.

Everything should be OK, for the translations of facets values, it's mandatory to reload the page to have the right translations. Maybe we can do something in ng-core to solve this, but at this time it's the behavior.

**Comment by pronguen** [comment]
@sebastiendeleze I tested the notifications and observed 2 problems:
1. Submission of a user without subdivision:
    * was sent to all moderators without subdivision ✔️ 
    * was not sent to all admin (should have been) ❗ 
2. A submission of a user with subdivision
    * was sent to all moderators of the same subdivision ✔️ 
    * was sent only to admin of the same subdivision (should have been sent to all admins) ❗
