### ISSUE TITLE
DEV and TEST subdomains

### ISSUE THREAD

**Issue by sebastiendeleze** [rero/sonar#19]
Setting up subdomains for DEV and TEST instances : 

- [ ] DEV --> dev.sonar.ch
- [ ] TEST --> test.sonar.ch

**Comment by sebastiendeleze** [comment]
As discussed with Philippe, it's OK for him to install SSL certificate with HAProxy. He set up a working example with a [custom domain](https://bozos.multivio.org).

Next step is to point dev|test.sonar.ch on HAProxy, but it seems to be complicated with the current hosting (I think it's netlify). @mmo, @pronguen could we discuss about that together?

**Comment by mmo** [comment]
We have to discuss with @philippe-rero and @iGormilhit in order to install sonar.ch locally instead of Netlify, but we have to define a proper deployment method.

**Comment by iGormilhit** [comment]
Maybe we could use a github PR webhook to deploy automatically, or something like that. In fact, it may be even easier than using netflify, **except for the preview build**, but it may be not needed anymore.

And then, the workflow could be the same for rero21.ch

**Comment by sebastiendeleze** [comment]
Duplicate of #398
