### ISSUE TITLE
Add a facet for searching document by date.

### ISSUE THREAD

**Issue by sebastiendeleze** [rero/sonar#213]

**Comment by sebastiendeleze** [comment]
<img width="292" alt="Capture d’écran 2020-06-05 à 15 32 19" src="https://user-images.githubusercontent.com/6112685/83882030-cea73980-a741-11ea-8005-2af6633abb47.png">

@pronguen Which solution do you prefer? Or maybe you think about an other alternative.

Please note that both need some work to work properly.

Option 1: Aggregations in ng-core need to be updated because we don't receive a string value as usually.
Option 2: This is not handled by invenio, I have to explode the range and send a custom query to ES.

**Comment by pronguen** [comment]
In Explore we have the following solution, which is good I think:
![image](https://user-images.githubusercontent.com/8154915/83996737-19e96400-a95d-11ea-960b-6f1fdef56a79.png)

For RERO ILS, Johnny created a small bar chart for the date facet; he was saying it was the standard fonction (in Invenio?). Maybe this would be the solution with least effort?
