### ISSUE TITLE
Email template

### ISSUE THREAD

**Issue by sebdeleze** [rero/sonar#252]
Add an email template for all emails sent. This can be easily created with tools like https://beefree.io/editor/.

**Comment by sebastiendeleze** [comment]
Here's a quick example of what we can do.

<img width="1183" alt="Capture d’écran 2020-06-19 à 08 37 58" src="https://user-images.githubusercontent.com/6112685/85105799-62313d80-b20b-11ea-9742-3f00aa2e22eb.png">
