### ISSUE TITLE
Extract date during import of documents

### ISSUE THREAD

**Issue by sebastiendeleze** [rero/sonar#254]
And display the field `provisionActivity.startDate` all the time

**Comment by sebastiendeleze** [comment]
Here's the different ways to populate `provisionActivity.startDate` from RERODOC documents:

1. Field 260$c --> Example: http://doc.rero.ch/record/323385/export/xm
2. Field 269$c --> Example: http://doc.rero.ch/record/328670/export/xm
3. Field 773$g (as long as `980$f` is of the type `ART_INBOOK`)  --> Example: http://doc.rero.ch/record/328059/export/xm

I tested a document for all the possibilities and the start date is set correctly.

Is there another field that can hold this start date?

**Comment by pronguen** [comment]
@sebastiendeleze Some documents have 2 dates ([example](http://doc.rero.ch/record/328670/export/xm)), so it would be great to prioritize:
* look first in field 260
* if no date found, look in 269
* if no date found, look in 773$g

**Comment by sebastiendeleze** [comment]
As mentioned here, now we take care of field 502$9 for getting a start date. This one has the lowest priority against the other fields
