### ISSUE TITLE
Modifies welcome e-mail for role "user"

### ISSUE THREAD

**Issue by pronguen** [rero/sonar#272]
* the new text is below
* be conscious that there are 2 cases for role "user"
  1. when it is created from the admin interface: welcome e-mail stays unchanged, the user is attached to an org
  1. when it is created from the public interface by the user himself/herself: **welcome e-mail to be adapted**, the user is not attached to any org

***

*Welcome e-mail for an account created by the user himself/herself:*

Object: Welcome to SONAR, the Swiss Open Access Repository!

Dear [user name or e-mail],

Please confirm your e-mail by clicking here: [Confirm e-mail](link)

To be able to deposit publications, you must be registered against a SONAR institution. For now, your account does not provide additional features, but in the future you will be able to create document lists and save requests.

Best regards

The SONAR team at RERO

E-mail: info.sonar@rero.ch
https://www.sonar.ch/
https://www.rero.ch

**Comment by mmo** [comment]
- OK
- Suggestion: The message tells the user: "To be able to deposit publications, you must be registered against a SONAR institution." It would be nice to say something about *how* that can be achived (eg. who to contact). (to be discussed)
