### ISSUE TITLE
Problem with users with role "user"

### ISSUE THREAD

**Issue by pronguen** [rero/sonar#273]
* when it is created from the admin interface, the user is attached to an org
* when it is created from the public interface by the user himself/herself, the user is not attached to any org. In this case, it is not possible for an admin to give him/her another role like "submitter" because he/she cannot display this user.

2 possible solutions
* when user is created from the public interface by the user himself/herself, it does not create a user resource, only an Invenio user
* the admin is able to search and display users of his/her org **+ users not attached to an org**

**Comment by mmo** [comment]
- OK
- Suggestion: Add a facet to user search, in order to filter users not attached to the organisation
