### ISSUE TITLE
DEV instance and sub domain activation

### ISSUE THREAD

**Issue by sebastiendeleze** [rero/sonar#3]
For @pronguen can validate the first tasks, we need to have a dev instance and a sub domain test.sonar.ch available. 

Who is responsible for that ?

**Comment by iGormilhit** [comment]
@sebastiendeleze I think you should talk with @philippe-rero for such topics.

**Comment by sebastiendeleze** [comment]
dev instance is up : https://sonardev.test.rero.ch/

thanks to Philippe and Johnny for your help
