### ISSUE TITLE
English analyzer does not work as expected

### ISSUE THREAD

**Issue by pronguen** [rero/sonar#334]
**Problem**
A search "dynamic reorganisation cortical network" gives 0 result, but "dynamic reorganization cortical network" gives the document https://sonar.test.rero.ch/global/documents/10506.

**Expected behaviour**
*reorganisation* should be considered as *reorganization* by the analyser.

**Comment by PascalRepond** [comment]
This seems not a SONAR problem but an ES problem, we have no power over ES standard analyzers behavior.
