### ISSUE TITLE
Conferences should be displayed with number, place and date

### ISSUE THREAD

**Issue by pronguen** [rero/sonar#338]
**Problem**
Conferences are display with only their name.

**Expected behaviour**
They should be displayed as follows:
Name (Number : Date : Place)

This concerns the public and professional views AND the brief and detailed views.

Example: http://data.rero.ch/01-1983505/html

**Comment by sebastiendeleze** [comment]
Just a dummy question, with type bf:Meeting, the role is mandatory in the editor, is that right? If yes, I will display something like this?: 

```
Conference name (Number : Date : Place) (contributor)
```

**Comment by pronguen** [comment]
Yes, the role is always mandatory. Indeed, it is not relevant to display it in the case of bf:Meeting. If you want to implement this exception, you are welcome, but it is not that important.
No, `number`, `date` and `place` should NOT be mandatory... there is always a case where one of them is not known at the cataloguing.

**Comment by sebastiendeleze** [comment]
Thanks!
