### ISSUE TITLE
Messages sent for "Forgot password" should be improved.

### ISSUE THREAD

**Issue by pronguen** [rero/sonar#343]
**Problem**

When I click on "Forgot password", I receive:
* the welcome message, even I am known by the system
* the reset password message

**Expected behaviour**

I should receive only the reset password message.
Text of reset password message:

```
SUBJECT: SONAR password reset

Dear [first name and last name],

Someone requested that the password for your SONAR account be reset.

Reset my password(+link)

If you didn't request this, you can ignore this e-mail. Your password won't change until you create a new password.

Best regards

[Institution name]

```
Template: https://postmarkapp.com/blog/password-reset-templates-best-practices

Text of password change confirmation
```
SUBJECT: Your SONAR password has been reset

Dear [first name and last name],

Your password has been successfully reset.

Best regards

[Institution name]
```

**Screenshot**

![image](https://user-images.githubusercontent.com/8154915/95973824-6ca7c080-0e14-11eb-9d8c-c45700d55cec.png)

**Comment by sebastiendeleze** [comment]
Unfortunately, we have no access to the user or the organization. The best we can do is:

```
SUBJECT: SONAR password reset

Dear user,

Someone requested that the password for your SONAR account be reset.

Reset my password(+link)

If you didn't request this, you can ignore this e-mail. Your password won't change until you create a new password.

Best regards

Your institution

```
