### ISSUE TITLE
Option to sort results by publication year, date added and relevance (ev. title)

### ISSUE THREAD

**Issue by sebdeleze** [rero/sonar#402]
In the document search (public/pro), sort by:
* Relevance [default]
* Date (newest)
* Date (oldest)
* Title

If easy to realise, add a sort option for all search:
* User: Relevance [default], Name
* Research project: Relevance [default], Name, Date (newest), Date (oldest)
* Collection: Relevance [default], Name
* Deposit: Relevance [default], Date added (newest), Date added (oldest)

**Comment by mmo** [comment]
Sort by date does to seem to work, either ascending or descending. (pro and public views)

**Comment by mmo** [comment]
It has been agreed that "Sort by date" should be based on field `provisionActivity.startDate`, but it is currently not the case in DEV.
