### ISSUE TITLE
Upload a full text publication

### ISSUE THREAD

**Issue by pronguen** [rero/sonar#43]
See corresponding mockup

Scenario:
* GORDANA Signs in
* SYSTEM Displays options for authenticated users
* GORDANA Clicks on “Add publication(s)”
* SYSTEM Displays four options (“1. Upload full-text”, “2. Paste a DOI”, “3. Import records from file (BibTeX, RIS, ...)”, “4. Create record manually”)
* GORDANA Chooses “1. Upload full-text”
* SYSTEM Displays a space for uploading a document
* GORDANA Drags and drops her PDF
* SYSTEM Extracts available metadata from PDF. Adds her as author of the document if this data is missing
* GORDANA Completes or corrects metadata, incl. diffusion rights, and save *(note: for now, create the editor only with metadata already in the data model)*
* SYSTEM Adds document to the institution of Gordana

**Comment by sebastiendeleze** [comment]
Here's a sample of xml extraction with Grobid: 
documents/documentation/projets/SONAR/dev/test_grobid_extraction/output.xml

And the base document: 
documents/documentation/projets/SONAR/dev/test_grobid_extraction/test.pdf

But I don't know if the source document is relevant, I found it on the web.

**Comment by pronguen** [comment]
It seems quite conclusive! I added four other documents in the file (preprint, postprint, thesis, conference paper). Could you launch Grobid on these documents in order to enlarge a bit the test sample?
