### ISSUE TITLE
The links of the table of content in the documentation are not working.

### ISSUE THREAD

**Issue by pronguen** [rero/sonar#450]
In the help, there is a table of content to navigate inside a page. The links are not correct.

Example on this page: https://sonar.test.rero.ch/help/deposit/

The link of the table of content
* are `https://sonar.test.rero.ch/#publication-rights`
* should be `https://sonar.test.rero.ch/help/deposit/#publication-rights`

**Comment by mmo** [comment]
There is problem when opening the user menu, as it is overridden by the table of contents. In that case, the overridden options of the menu are not clickable (MacOS Safari).
<img width="412" alt="Screenshot 2021-02-01 at 13 37 53" src="https://user-images.githubusercontent.com/52756/106461425-0adb9700-6495-11eb-93d1-d9235578f268.png">
