### ISSUE TITLE
Editor for bibliographic metadata

### ISSUE THREAD

**Issue by pronguen** [rero/sonar#52]

**Comment by sebastiendeleze** [comment]
TODO: 

- [ ] Save metadata in database for each files
- [ ] Convert input text for publication date to input date
- [ ] Add default values for repeatable fields
- [ ] Create briew view for deposit
- [ ] Create detail view for deposit
- [ ] Search in MEF for contributors
- [ ] Show status of the deposit
- [ ] Remove full-text file when a file is removed
