### ISSUE TITLE
Improve deposit editor

### ISSUE THREAD

**Issue by pronguen** [rero/sonar#569]
- The identifier sub-fields are grouped with a grey vertical bar (see screenshot). It would be nice to also group:
    - Title in other language: language, title
    - Contained in (host document): document, year, pages, publisher, editors
![image](https://user-images.githubusercontent.com/8154915/119642512-1889a380-be1b-11eb-8921-04a1c16d0819.png)

- Replace "editors" by "authors/editors", because in French they have the same translation:
![image](https://user-images.githubusercontent.com/8154915/119643435-03614480-be1c-11eb-8fbb-276e7853535f.png)

- Remove the field validation on "editors"/"authors". We should be able to enter a corporate body (ex. "HEP BEJUNE") as author, without comma.
- Replace "Contained in (host document)" by "Contained in (journal, book, proceedings)"
- Remove the field "editors"/"authors" for document type "Journal article" (c_6501)
- `partOf`: `volume` and `number` should be validated and contain only integer.
- `partOf`: is it possible to remove the field from the deposit editor: at the document creation, `provisionActivity.startDate` and `parfOf.year` use both the document date of the deposit (only for 'coar:c_3248', 'coar:c_5794', 'coar:c_6670', 'coar:c_3e5a', 'coar:c_beb9', 'coar:c_6501', 'coar:c_998f', 'coar:c_dcae04bc')?
- rename "Subjects" into "Keywords" (also in singular)
- step 5, field "license", set as default value "License undefined"
    - in the license enum, change the two values
        - "Other OA / license undefined" > "License undefined"
        - "Not OA / Rights reserved" > "Rights reserved"
- step 5, add field "oa_status", optional, with label "Open access status"
- step 4 (projects)
    - add a date picker for the 2 dates
    - move the examples for the 2 dates ("Example: 2019-05-05") from the description (tooltip in the form) to the placeholder, in order to be compliant with our [guidelines](https://github.com/rero/developer-resources/blob/master/interface/layout-charter.md#4-form-design).

**Comment by mmo** [comment]
>   * in the license enum, change the two values **(to be confirmed by @mmo )**
>     
>     * "Other OA / license undefined" > "License undefined"
>     * "Not OA / Rights reserved" > "Rights reserved"

Confirmed!
