### ISSUE TITLE
Import publications from swisscovery

### ISSUE THREAD

**Issue by pronguen** [rero/sonar#610]
**Expected workflow**
1. From the deposit form, it is possible to import the data from the PDF, but also from Swisscovery (in the future: Past a DOI and import from Crossref). This should be possible even if no file was uploaded in SONAR.
    * [Nice to have] the import feature is also available in the document editor
![image](https://user-images.githubusercontent.com/8154915/127194985-8bbe201c-9885-43de-9ac5-7ab50631055b.png)
2. This open a modal window with title "Import metadata from swisscovery"
    * It has one dropdown where the search input can be chosen: Everywhere / DOI / ID swisscovery (MARC 001) / ISBN / ISSN
        * Everywhere is the default value
    * Next to the dropdown there is an input field for the search
    * Below, the following text is displayed: "If data has been entered in the form, it will be overwritten."
3. The first result given by SRU is automatically imported in the form.

**Spec**
SRU (explain): https://swisscovery.slsp.ch/view/sru/41SLSP_NETWORK?version=1.2&operation=explain
SRU (query example): https://swisscovery.slsp.ch/view/sru/41SLSP_NETWORK?operation=searchRetrieve&version=1.1&query=(all_for_ui=9783495491713)&recordSchema=marcxml&maximumRecords=1&startRecord=1
MARC21 of swisscovery: https://access.rdatoolkit.org/Document/Document?documentId=09adb0ac-f0bb-404c-aaba-0606c0fd0c19

Search
* Everywhere: `all_for_ui` (it should be possible to enter various search terms)
* DOI: `digital_object_identifier` ([example](https://swisscovery.slsp.ch/view/sru/41SLSP_NETWORK?operation=searchRetrieve&version=1.1&query=(digital_object_identifier=10.1111/aman.13158)&recordSchema=marcxml&maximumRecords=1&startRecord=1))
* ID swisscovery (MARC 001): `mms_id` ([example](https://swisscovery.slsp.ch/view/sru/41SLSP_NETWORK?operation=searchRetrieve&version=1.1&query=(mms_id=991055600959705501)&recordSchema=marcxml&maximumRecords=1&startRecord=1))
* ISBN: `isbn`
* ISSN: `issn`

**Comment by pronguen** [comment]
Test of the feature:
- [ ] Subtitle not mapped (245$b). Example: 991011495419705501
- [ ] Ongoing / to be completed

**Comment by sebastiendeleze** [comment]
> Search
> 
> * [ ]  Search _Everywhere_ does work only within one field. Should work even if you search a term from the title combined the author name for example.
>   ![image](https://user-images.githubusercontent.com/8154915/130853927-ede6f874-4607-4bac-b86b-1bd26fc483cf.png)
> * [ ]  In any case, the system should display the number of results found.
>   
>   * [nice to have] Ideally in the very best case, we have the number of results and the 5 firsts of them displayed with title and link to the swisscovery detailed view (opened in a new tab). The user can choose which one he/she wants to import.
> * [ ]  When clicking on "Import from swisscovery", the pointer should be automatically placed on the field "Scope" to facilitate keyboard navigation.

I propose to create another issue for handling that.
