### ISSUE TITLE
Show header with collection when it is selected through the facet [2]

### ISSUE THREAD

**Issue by mmo** [rero/sonar#668]
## Current situation

When selecting a value in the "Collection" facet, the documents are filtered as a usual facet.

## Expected behaviour

When selecting a value in the "Collection" facet, the header of the collection (see image below as an example) is shown on top of the page.

![image](https://user-images.githubusercontent.com/8154915/160800500-56720b2d-512c-4923-8a15-bf1a90d12452.png)

**Comment by pronguen** [comment]
@mmo Are we sure we want this behaviour, and that it is a priority?

When displaying a collection header, I observed that the collection facet is then hidden... it would be impossible to filter documents by selecting 2 collections. Can you confirm this or add it to be discuss at next PO group?
