### ISSUE TITLE
Migrate data from RERO DOC

### ISSUE THREAD

**Issue by sebastiendeleze** [rero/sonar#76]

**Comment by pronguen** [comment]
Via OAI-PMH, migrer les sets suivants:
* unifr, unisi, nl-epfl, nl-ethz, nl-fachhochschulen, nl-lib4ri, nl-unibas, nl-unibe, nl-unifr, nl-unige, nl-unil, nl-unilu, nl-unine, nl-unisg, nl-usi, nl-uzh

**Comment by sebastiendeleze** [comment]
@pronguen you can find [here](https://gist.github.com/sebastiendeleze/1802f36c75f6cc7b607e65984b6a11e8#file-missing-txt) the properties that are not taken into account during import process.

**Comment by sebastiendeleze** [comment]
Someone can give me an example of a RERODOC record which owns several files, so I can check if all the files are imported correctly, please?

**Comment by sebastiendeleze** [comment]
@jma Can you give me the library for checking text extraction of PDF files?

**Comment by pronguen** [comment]
> Someone can give me an example of a RERODOC record which owns several files, so I can check if all the files are imported correctly, please?

@sebastiendeleze Here an example, but not part of USI/UNIFR: http://doc.rero.ch/record/305541?ln=fr
