### ISSUE TITLE
OAI-PMH error with the verb `GetRecord`

### ISSUE THREAD

**Issue by mmo** [rero/sonar#783]
The verb `GetRecord` generates a "500 Internal Server Error" message.

Example: https://sonardev.test.rero.ch/oai2d?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:sonar.ch:60
(Note: this URL may become invalid if data on SONAR DEV is removed - replace `60` by some other document id, in that case.)

**Comment by pronguen** [comment]
@Garfield-fr This issue seems solved. Do you confirm?

**Comment by Garfield-fr** [comment]
> @Garfield-fr This issue seems solved. Do you confirm?

Yes

**Comment by pronguen** [comment]
Solve, probably by https://github.com/rero/sonar/pull/793
